FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json tsconfig.base.json ./
COPY shared/package.json shared/package.json
COPY shared/tsconfig.json shared/tsconfig.json
COPY worker/package.json worker/package.json
COPY worker/tsconfig.json worker/tsconfig.json

RUN npm ci

COPY shared shared
COPY worker worker

EXPOSE 8081

CMD ["npm", "run", "-w", "worker", "start"]
